### ISSUE TITLE
Load balancing, clustering DBs

### ISSUE THREAD

**Issue by 78bash** [ubermail/ubermail#31]
Ansible noob here,
How does one go about load balancing the ubermail instance as well as clustering the databases?

**Comment by killua-eu** [comment]
The quick answer, if you need load balancing or DB clustering, submit a PR. The long answer:

I assume that by load balancing you mean having two postfix instances (two mx servers with separate IP addresses on different hosts to deal with outages)? This role doesn't really have the configuration options for this but it should be relitvely easy to add if you wanna do a PR. The reason is that all well-configured mailservers will redeliver e-mails later if the receiving mx server is down and for most users its an added layer of complexity in an already complex stack.

Same goes with clustering databases. I can't really imagine a scenario when you'd need the dbs clustered, unless you deploy this role for a large freemail service for which ubermail isn't really designed. You'd sooner hit other problems (disk-bound IO issues on Dovecot or Solr just eating away all the RAM and CPU).

Hope this answers your questions :)
